-- SelfDesk Fresh Supabase Setup
-- Run this entire script in Supabase SQL Editor
-- Creates all tables and RLS policies for the new auth system

-- ========================================
-- 1. CREATE TABLES
-- ========================================

-- app_settings: Stores user theme preferences
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,  -- Will store auth.uid()::text, unique for upsert
    current_theme TEXT NOT NULL DEFAULT 'light',
    theme_colors JSONB NOT NULL DEFAULT '{"primary":"#3b82f6","secondary":"#64748b","background":"#ffffff","surface":"#f8fafc","text_primary":"#1e293b","text_secondary":"#64748b","text_tertiary":"#94a3b8","border":"#e2e8f0","danger":"#ef4444","warning":"#f59e0b","success":"#10b981","info":"#06b6d4"}',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- folders: Note organization (created first since notes references it)
CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES folders(id) ON DELETE CASCADE,
    color TEXT DEFAULT '#64748b',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- notes: User markdown notes (references folders)
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT DEFAULT '',
    folder_id BIGINT REFERENCES folders(id) ON DELETE SET NULL,
    is_favorite BOOLEAN DEFAULT FALSE,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- files: File metadata (stored in Telegram)
CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    file_type TEXT NOT NULL, -- 'document', 'image', 'video', 'audio'
    telegram_file_id TEXT NOT NULL,
    folder_id BIGINT REFERENCES folders(id) ON DELETE SET NULL,
    size_bytes BIGINT,
    mime_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- theme_presets: User custom themes
CREATE TABLE IF NOT EXISTS theme_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    colors JSONB NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- message_metadata: Chat message metadata
CREATE TABLE IF NOT EXISTS message_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    telegram_message_id BIGINT NOT NULL,
    message_type TEXT NOT NULL, -- 'user' or 'bot'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    has_file BOOLEAN DEFAULT FALSE,
    file_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- 2. CREATE INDEXES
-- ========================================

CREATE INDEX IF NOT EXISTS idx_app_settings_user_id ON app_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_user_id ON notes(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_folder_id ON notes(folder_id);
CREATE INDEX IF NOT EXISTS idx_folders_user_id ON folders(user_id);
CREATE INDEX IF NOT EXISTS idx_folders_parent_id ON folders(parent_id);
CREATE INDEX IF NOT EXISTS idx_files_user_id ON files(user_id);
CREATE INDEX IF NOT EXISTS idx_files_folder_id ON files(folder_id);
CREATE INDEX IF NOT EXISTS idx_theme_presets_user_id ON theme_presets(user_id);
CREATE INDEX IF NOT EXISTS idx_message_metadata_user_id ON message_metadata(user_id);
CREATE INDEX IF NOT EXISTS idx_message_metadata_telegram_id ON message_metadata(telegram_message_id);

-- ========================================
-- 3. ENABLE RLS
-- ========================================

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE theme_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_metadata ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 4. CREATE RLS POLICIES
-- ========================================

-- app_settings policies
CREATE POLICY "Users can view own app_settings" ON app_settings
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own app_settings" ON app_settings
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own app_settings" ON app_settings
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own app_settings" ON app_settings
    FOR DELETE USING (user_id = auth.uid()::text);

-- notes policies
CREATE POLICY "Users can view own notes" ON notes
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own notes" ON notes
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own notes" ON notes
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own notes" ON notes
    FOR DELETE USING (user_id = auth.uid()::text);

-- folders policies
CREATE POLICY "Users can view own folders" ON folders
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own folders" ON folders
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own folders" ON folders
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own folders" ON folders
    FOR DELETE USING (user_id = auth.uid()::text);

-- files policies
CREATE POLICY "Users can view own files" ON files
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own files" ON files
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own files" ON files
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own files" ON files
    FOR DELETE USING (user_id = auth.uid()::text);

-- theme_presets policies
CREATE POLICY "Users can view own theme_presets" ON theme_presets
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own theme_presets" ON theme_presets
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own theme_presets" ON theme_presets
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own theme_presets" ON theme_presets
    FOR DELETE USING (user_id = auth.uid()::text);

-- message_metadata policies
CREATE POLICY "Users can view own message_metadata" ON message_metadata
    FOR SELECT USING (user_id = auth.uid()::text);

CREATE POLICY "Users can insert own message_metadata" ON message_metadata
    FOR INSERT WITH CHECK (user_id = auth.uid()::text);

CREATE POLICY "Users can update own message_metadata" ON message_metadata
    FOR UPDATE USING (user_id = auth.uid()::text);

CREATE POLICY "Users can delete own message_metadata" ON message_metadata
    FOR DELETE USING (user_id = auth.uid()::text);

-- ========================================
-- 5. GRANT PERMISSIONS
-- ========================================

GRANT ALL ON app_settings TO authenticated;
GRANT ALL ON notes TO authenticated;
GRANT ALL ON folders TO authenticated;
GRANT ALL ON files TO authenticated;
GRANT ALL ON theme_presets TO authenticated;
GRANT ALL ON message_metadata TO authenticated;

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO authenticated;

-- Grant usage on sequences for auto-incrementing IDs
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ========================================
-- 6. CREATE FUNCTIONS (Optional)
-- ========================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON app_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_notes_updated_at BEFORE UPDATE ON notes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ========================================
-- 7. SETUP COMPLETE
-- ========================================

-- Insert default settings for new users
-- This will be handled by the application when users first log in
-- But we can create a function to initialize user settings if needed

CREATE OR REPLACE FUNCTION initialize_user_settings(user_uuid TEXT)
RETURNS VOID AS $$
BEGIN
    INSERT INTO app_settings (user_id, current_theme, theme_colors)
    VALUES (user_uuid, 'light', '{"primary":"#3b82f6","secondary":"#64748b","background":"#ffffff","surface":"#f8fafc","text_primary":"#1e293b","text_secondary":"#64748b","text_tertiary":"#94a3b8","border":"#e2e8f0","danger":"#ef4444","warning":"#f59e0b","success":"#10b981","info":"#06b6d4"}')
    ON CONFLICT (user_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

SELECT 'SelfDesk database setup complete!' as status;
